disabled_rules: # rule identifiers to exclude from running
  - line_length
  - function_body_length
  - todo
# Test force unwrepping ocasionally
#opt_in_rules:
#  - force_unwrapping
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - CommandLine
  - iOSTestApp
  - macTestApp
  - tvTestApp
  - watchTestApp
  - watchTestApp Extension
type_name:
  excluded:
    - OK
variable_name:
  max_length:
    warning: 80
    error: 100
  excluded: # excluded via string array
    - id
    - URL
type_body_length:
  warning: 300
  error: 500
file_length:
  warning: 600
  error: 800
